language: go

install:
  - go get github.com/gohugoio/hugo

before_script:
  - rm -rf public

script:
  - hugo --minify
  - echo next.expertanalytics.no > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  repo: expertanalytics/expertanalytics.github.io
  on:
    branch: master
